service: email-service


provider:
  name: aws
  runtime: python3.9

plugins:
  - serverless-offline

functions:
  home:
    handler: handler.home
    events:
      - http:
          path: /
          method: get

  sendEmail:
    handler: handler.send_email
    events:
      - http:
          path: send-email
          method: post
